GROCERIES = [
    "4lb cosmic",
    "almndcracker",
    "apothic red",
    "apples",
    "applesauce",
    "avocado",
    "bacon",
    "baking cocoa",
    "baking powder",
    "baking soda",
    "banana",
    "beans",
    "beef",
    "beefsticks",
    "blueberries",
    "bok choy",
    "brbn",
    "bread",
    "broth",
    "butter",
    "bv blueberry",
    "cake-vanilla",
    "cake" "carrots",
    "carrot6lb",
    "cashews",
    "cereal",
    "cheese",
    "chicken",
    "chip",
    "chips",
    "chocolate",
    "cilantro",
    "clementines",
    "coca-cola",
    "coconut flakes",
    "cod",
    "cooking spray",
    "corn starch",
    "distilled water",
    "dough",
    "dressing",
    "drinking water",
    "egg whites",
    "eggs",
    "enchilada",
    "flour",
    "fruit roll",
    "ginger root",
    "gluten" "goodlespack" "grape",
    "goodlespack",
    "ground cinnamon",
    "half and half",
    "ham",
    "hash brown",
    "honey",
    "hot dog",
    "instant coffee",
    "juice",
    "ks lbc",
    "ks micro pop",
    "ks u/s qtrs",
    "lacroix",
    "lime",
    "lunchable",
    "magic spoon",
    "mango",
    "marinara",
    "marshmallows",
    "meatballs",
    "milk",
    "morsels",
    "mushroom",
    "noodles",
    "nutritional shake",
    "oats",
    "olive",
    "onions",
    "oranges",
    "org csr kit",
    "org frt bar",
    "parmigiano",
    "parsley",
    "pasta",
    "peanut",
    "pecans",
    "pepper",
    "peppermint extract",
    "peru 2#",
    "pickle",
    "pie crust",
    "pineapple",
    "pizza",
    "potato",
    "preserves",
    "pretzel",
    "pure pumpkin",
    "quinoa",
    "raisins",
    "rao",
    "rice",
    "salsa",
    "sausage",
    "skippy",
    "snacks",
    "soy sauce",
    "sprinkle",
    "sugar",
    "sweet thins",
    "syrup",
    "taco" "tacos",
    "that's it",
    "tofu",
    "tofu",
    "tomato",
    "tortillas",
    "trail mix",
    "turkey",
    "veggie rolls",
    "water",
    "whipping cream",
    "yeast",
    "yogurt",
    "zbar",
    "green bell",
    "seasoning",
]
