GROCERIES = [
    "4lb cosmic",
    "almndcracker",
    "apothic red",
    "apple",
    "apples",
    "applesauce",
    "apricots",
    "artichoke",
    "arugula",
    "asparagus",
    "avocado",
    "bacon",
    "bagels",
    "baking cocoa",
    "baking powder",
    "baking soda",
    "banana",
    "beans",
    "beef",
    "beefsticks",
    "beet",
    "bell pepper",
    "black bean",
    "blackberry",
    "blueberries",
    "blueberry",
    "bok choy",
    "brbn",
    "bread",
    "broccoli",
    "broth",
    "brussels sprouts",
    "buffalo wild wings",
    "buffalo wing",
    "butter",
    "bv blueberry",
    "cabbage",
    "cake-vanilla",
    "cake" "carrots",
    "cantaloupe",
    "carrot",
    "carrot6lb",
    "cashews",
    "cassava",
    "cauliflower",
    "celery",
    "cereal",
    "cheese",
    "cherries",
    "chicken",
    "chickpea",
    "chiles",
    "chip",
    "chips",
    "chocolate",
    "cilantro",
    "clementines",
    "coca-cola",
    "coconut flakes",
    "coconut",
    "cod",
    "cooking spray",
    "corn starch",
    "corn",
    "crackers",
    "cranberries",
    "cucumber",
    "dates",
    "deli",
    "dill",
    "distilled water",
    "dough",
    "dressing",
    "drinking water",
    "dumplings",
    "edamame",
    "egg whites",
    "eggplant",
    "eggs",
    "enchilada",
    "fennel",
    "figs",
    "flour",
    "fruit roll",
    "garlic knots",
    "ginger root",
    "gluten" "goodlespack" "grape",
    "gnocchi",
    "gogo squeeze",
    "goodlespack",
    "grape",
    "grapefruit",
    "green bean",
    "green beans",
    "green bell",
    "ground cinnamon",
    "half & half",
    "half and half",
    "ham",
    "hash brown",
    "hawaiian sweet rolls",
    "honey",
    "honeydew",
    "hot dog",
    "hummus",
    "instant coffee",
    "jicama",
    "juice",
    "kale",
    "kidney bean",
    "kiwi",
    "ks albacore",
    "ks lbc",
    "ks micro pop",
    "ks pnut butr",
    "ks sparkling",
    "ks strawpres",
    "ks thick cut",
    "ks u/s qtrs",
    "lacroix",
    "lavash",
    "lemon",
    "lentil",
    "lesser evil",
    "lettuce",
    "lima bean",
    "lime",
    "liquid i.v.",
    "lunchable",
    "madegoodmini",
    "magic spoon",
    "mango",
    "marinade",
    "marinara",
    "marsala",
    "marshmallows",
    "meatballs",
    "milk",
    "morsels",
    "mtball",
    "muffins",
    "mushroom",
    "navy bean",
    "noodles",
    "nutritional shake",
    "oats",
    "olive",
    "onion",
    "onions",
    "orange",
    "oranges",
    "org csr kit",
    "org frt bar",
    "papaya",
    "parmigiano",
    "parsley",
    "parsnip",
    "pasta",
    "pea",
    "peach",
    "peanut",
    "pear",
    "pecans",
    "pepper",
    "peppermint extract",
    "peru 2#",
    "pickle",
    "pie crust",
    "pineapple",
    "pinto bean",
    "pirate's booty",
    "pizza",
    "plum",
    "pomegranate",
    "potato",
    "preserves",
    "pretzel",
    "prunes",
    "pumpkin",
    "pure pumpkin",
    "queso",
    "quinoa",
    "radish",
    "raisins",
    "rao",
    "raspberry",
    "rice",
    "romaine",
    "rotisserie",
    "rutabaga",
    "salad",
    "salsa",
    "sauce",
    "sausage",
    "seasoning",
    "seltzer",
    "sesame seed oil",
    "shrimp",
    "skippy",
    "snacks",
    "snap peas",
    "soft taco",
    "sonic tots",
    "soy sauce",
    "soybean",
    "spinach",
    "sprinkle",
    "squash",
    "strawberries",
    "strawberry",
    "sugar",
    "sweet potato",
    "sweet thins",
    "syrup",
    "taco" "tacos",
    "taro",
    "that's it",
    "tofu",
    "tomato",
    "tortilla",
    "tortillas",
    "trail mix",
    "trubar",
    "turkey",
    "turnip",
    "veggie rolls",
    "waffles",
    "water",
    "watermelon",
    "wellsley farm",
    "wellsley farms",
    "whipping cream",
    "whole bean coffee",
    "whole cran",
    "wilde buff",
    "yam",
    "yeast",
    "yoggies",
    "yogurt",
    "zbar",
    "zucchini",
    "cold brew",
    "cake mix",
    "sprite",
    "crescent rolls",
]
