class CategoryOrganizer:
    def __init__(self):
        self.categories = {
            "Personal": [
                "shampoo",
                "tampons",
                "conditioner",
                "toothpaste",
                "deoderant",
                "eyeliner",
                "blush",
                "lotion",
                "cosmetics",
                "mascara",
                "makeup",
                "face serum",
                "facial",
                "scalp treatment",
                "moisturizer",
                "toothbrush",
                "razor",
                "ponytail",
                "sunscreen",
                "brightening serum",
                "bar soap",
                "brush"
            ],
            "Clothing": [
                "sweater",
                "socks",
                "t-shirt",
                "underwear",
                "shoe",
                "shirt",
                "body suit",
                "tights",
                "gloves",
                "boots",
                "pullover",
                "clogs",
                "leggings",
                "ballet flats",
                "hoodie",
                "jkt",
                "joggers",
                "puma sock",
                "pumaliner8pr",
                "sandals",
                "utility short",
                "pants",
                "shorts",
                "skort",
                "romper",
                "blouse",
                "dress"
            ],
            "Home Supplies": [
                "aluminum foil",
                "bath tissue",
                "batteries",
                "bowls",
                "broom",
                "cascplatplus",
                "cleaner",
                "cleaners",
                "cleaning",
                "coffee filter",
                "command 8pk heavy phs adhesives",
                "command strips",
                "dawn powerws",
                "detergent",
                "dish soap",
                "disinfectant",
                "disinfecting wipe",
                "dixie to go",
                "dryer sheets",
                "extension cord",
                "freeze block",
                "hand soap",
                "hangers",
                "ks dish pacs",
                "laundry",
                "light bulb",
                "lysol", 
                "mop",
                "outlet",
                "paper towel",
                "parchment paper",
                "plate",
                "snack bag",
                "sponges",
                "straws",
                "swiffer wet",
                "thermacell refills",
                "tissue",
                "toiletwand",
                "towel",
                "trash bag",
                "trash can",
                "utility pans",
                "vacuum",
                "ziploc",
                "zipper bags",
                "clorox",
                "duracell",
                "ks bath",
                "food storage",
                "disposable cups",
                "paper plates",
                "table cover",
                "toilet paper",
                "paper towels",
                "dish soap"
            ],
            "Medical": [
                "cough drops",
                "throat drops",
                "vicks",
                "ibuprofen",
                "medicine",
                "supplement",
                "softgels",
                "pregnancy test",
                "sleep-aid",
                "mylanta",
                "tums"
            ],
            "Baby Supplies": ["diapers", "baby wipes", "diaper", "baby wipe"],
            "Gifts": [
                "wrapping paper",
                "gift wrap",
                "inflatables yard",
                "christmas tree",
                "nutcraker",
            ],
            "Furnishings": ["curtain","thread count","bedding","comforter","pillow"],
            "Groceries": [
                "4lb cosmic",
                "larabar",
                "ice cream",
                "great value",
                "almndcracker",
                "apothic red",
                "creamer",
                "ranch dip",
                "apple",
                "apples",
                "applesauce",
                "apricots",
                "artichoke",
                "arugula",
                "asparagus",
                "avocado",
                "bacon",
                "bagels",
                "baking cocoa",
                "baking powder",
                "baking soda",
                "banana",
                "beans",
                "beef",
                "beefsticks",
                "beet",
                "bell pepper",
                "black bean",
                "blackberry",
                "blueberries",
                "blueberry",
                "bok choy",
                "brbn",
                "bread",
                "broccoli",
                "broth",
                "brussels sprouts",
                "buffalo wild wings",
                "buffalo wing",
                "butter",
                "bv blueberry",
                "cabbage",
                "cake-vanilla",
                "cake" "carrots",
                "cantaloupe",
                "carrot",
                "carrot6lb",
                "cashews",
                "cassava",
                "cauliflower",
                "celery",
                "cereal",
                "cheese",
                "cherries",
                "chicken",
                "chickpea",
                "chiles",
                "chip",
                "chips",
                "chocolate",
                "cilantro",
                "clementines",
                "coca-cola",
                "coconut flakes",
                "coconut",
                "cod",
                "cooking spray",
                "corn starch",
                "corn",
                "crackers",
                "cranberries",
                "cucumber",
                "dates",
                "deli",
                "dill",
                "distilled water",
                "dough",
                "dressing",
                "drinking water",
                "dumplings",
                "edamame",
                "egg whites",
                "eggplant",
                "eggs",
                "enchilada",
                "fennel",
                "figs",
                "flour",
                "fruit roll",
                "garlic knots",
                "ginger root",
                "gluten" "goodlespack" "grape",
                "gnocchi",
                "gogo squeeze",
                "goodlespack",
                "grape",
                "grapefruit",
                "green bean",
                "green beans",
                "green bell",
                "ground cinnamon",
                "half & half",
                "half and half",
                "ham",
                "hash brown",
                "hawaiian sweet rolls",
                "honey",
                "honeydew",
                "hot dog",
                "hummus",
                "instant coffee",
                "jicama",
                "juice",
                "kale",
                "kidney bean",
                "kiwi",
                "ks albacore",
                "ks lbc",
                "ks micro pop",
                "ks pnut butr",
                "ks sparkling",
                "ks strawpres",
                "ks thick cut",
                "ks u/s qtrs",
                "lacroix",
                "lavash",
                "lemon",
                "lentil",
                "lesser evil",
                "lettuce",
                "lima bean",
                "lime",
                "liquid i.v.",
                "lunchable",
                "madegoodmini",
                "magic spoon",
                "mango",
                "marinade",
                "marinara",
                "marsala",
                "marshmallows",
                "meatballs",
                "milk",
                "morsels",
                "mtball",
                "muffins",
                "mushroom",
                "navy bean",
                "noodles",
                "nutritional shake",
                "oats",
                "olive",
                "onion",
                "onions",
                "orange",
                "oranges",
                "org csr kit",
                "org frt bar",
                "papaya",
                "parmigiano",
                "parsley",
                "parsnip",
                "pasta",
                "pea",
                "peach",
                "peanut",
                "pear",
                "pecans",
                "pepper",
                "peppermint extract",
                "peru 2#",
                "pickle",
                "pie crust",
                "pineapple",
                "pinto bean",
                "pirate's booty",
                "pizza",
                "plum",
                "pomegranate",
                "potato",
                "preserves",
                "pretzel",
                "prunes",
                "pumpkin",
                "pure pumpkin",
                "queso",
                "quinoa",
                "radish",
                "raisins",
                "rao",
                "raspberry",
                "rice",
                "romaine",
                "rotisserie",
                "rutabaga",
                "salad",
                "salsa",
                "sauce",
                "sausage",
                "seasoning",
                "seltzer",
                "sesame seed oil",
                "shrimp",
                "skippy",
                "snacks",
                "snap peas",
                "soft taco",
                "sonic tots",
                "soy sauce",
                "soybean",
                "spinach",
                "sprinkle",
                "squash",
                "strawberries",
                "strawberry",
                "sugar",
                "sweet potato",
                "sweet thins",
                "syrup",
                "taco" "tacos",
                "taro",
                "that's it",
                "tofu",
                "tomato",
                "tortilla",
                "tortillas",
                "trail mix",
                "trubar",
                "turkey",
                "turnip",
                "veggie rolls",
                "waffles",
                "water",
                "watermelon",
                "wellsley farm",
                "wellsley farms",
                "whipping cream",
                "whole bean coffee",
                "whole cran",
                "wilde buff",
                "yam",
                "yeast",
                "yoggies",
                "yogurt",
                "zbar",
                "zucchini",
                "cold brew",
                "cake mix",
                "sprite",
                "crescent rolls",
                "salt & vinegar",
                "red wine vinegar",
                "vinegar",
                "mayonnaise",
                "walnuts",
                "veggie dip",
                "naan",
                "waffle",
                "pancake",
                "cole slaw"
            ],
            "Education": [
                "highlighter",
                "flash cards: multiplication 0 - 12 (other)"
            ],
            "Other": [],
        }
        self.organized_items = {category: [] for category in self.categories}

    def organize_item(self, item_name, item_price):
        for category, keywords in self.categories.items():
            if any(keyword in item_name.lower() for keyword in keywords):
                self.organized_items[category].append(
                    {"name": item_name, "price": item_price}
                )
                return  # Exit after assigning to the first matching category
        # If no category matches, add to "Other"
        self.organized_items["Other"].append(
            {"name": item_name, "price": item_price}
        )
    
    def get_summary(self):
        summary = {}
        for category, items in self.organized_items.items():
            total_price = sum(item['price'] for item in items)
            summary[category] = {
                'items': items,
                'total_price': total_price
            }
        return summary